### ISSUE TITLE
launch.py: error: argument --master_port: invalid int value: '--work-dir'

### ISSUE THREAD

**Issue by Shirlleyhan** [Chan-Sun/IFSDD#1]
您好，完全按照您的步骤进行训练，出现了如题报错。想请问一下如何在单机单GPU上实现您的代码训练？另外，是否文件中有些绝对路径要进行相应修改？盼回复，感激不尽

**Comment by 2252033991** [comment]
请问您有找到LKA损失函数的相关代码吗，我没有在作者的代码中看到
