### ISSUE TITLE
LKA code

### ISSUE THREAD

**Issue by 2252033991** [Chan-Sun/IFSDD#3]
Your work is great, I would like to ask where the loss function code is in the FKA part, I don't see the loss function ChannelWiseDivergence this type of code introduction.

**Comment by Chan-Sun** [comment]
Hi！Sorry for the confusion. This work has been modified several times for submissions. So the code might not be consistent with the description with the paper. 

I will update the whole code recently.

**Comment by 2252033991** [comment]
Thank you, in addition, please give a clear introduction to the specific location of the dataset picture, in my opinion, your dataset uses coco format, so what is the image storage path, is it train2014?

**Comment by 2252033991** [comment]
> 嗨！很抱歉造成混乱。这项工作已经过多次修改以提交。因此，代码可能与论文的描述不一致。
> 
> 我最近将更新整个代码。

Thank you, in addition, please give a clear introduction to the specific location of the dataset picture, in my opinion, your dataset uses coco format, so what is the image storage path, is it train2014?
