### ISSUE TITLE
GeneralDistill: MMFewShotArchitecture: ./weights/frcn_r101_split1_fine-tuning.pth can not be found.

### ISSUE THREAD

**Issue by ThelilinNB** [Chan-Sun/IFSDD#4]
你好 请问这个问题怎么解决，并没有给出需要的权重在哪里获取，谢谢

**Comment by Chan-Sun** [comment]
Hi, we generally follow the paradigm of TFA, so you can learn the process from [mmfewshot](https://github.com/open-mmlab/mmfewshot/blob/main/configs/detection/tfa/README.md) and [TFA Official](https://github.com/ucbdrive/few-shot-object-detection)

This checkpoint is fetched by pretraining and model dimension expansion. Sorry I do not make it clear before. 

REAMDE file has been updated. you can now check the process. Commands for pretrain and fine-tuning can also be found in [./shell/train.sh](https://github.com/Chan-Sun/IFSDD/blob/main/shell/train.sh)
