### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'dataset'

### ISSUE THREAD

**Issue by ThelilinNB** [Chan-Sun/IFSDD#5]
thank you very much for your solution to the previous problem. Now I have encountered such a problem again. Do you have any solution

**Comment by yanglong0228** [comment]
i met this situation like you

**Comment by yanglong0228** [comment]
i met this situation as you ever

**Comment by Chan-Sun** [comment]
Hi, sorry for the delay.

I have fixed the issue and updated the README file. It may solve most of the problems. 

Let me know if you have any further issues.
